### ISSUE TITLE
Plotter Nav Issue

### ISSUE THREAD

**Issue by Damarik** [RexTheCapt/EdTools#1] opened 2022-02-01 15:55 UTC
Plotter continually moves 2 jumps ahead when arriving at new system. Causes issues with Odyssey Plotter, which chooses to take a different route than the one expected, due to either shorter distance or fuel consumption.

Jump to Jump plotting fails after about 10-15 consecutive jumps, and begins skipping two systems.

**Comment by RexTheCapt** [comment] 2022-02-01 16:17
I think i know what the problem is... gonna try to implement a fix.

**Comment by RexTheCapt** [comment] 2022-02-01 16:41
I think i have made a fix for it. You can download the update from [here](https://github.com/RexTheCapt/EdTools/releases/tag/V0.1.1)

Also, whenever I use an neutro plotter (does not matter which) i never re-plot in game unless i am with an neutron star.

**Comment by RexTheCapt** [comment] 2022-02-02 06:34
So we talked through private message and found out my previous fix kinda worked, but made a small mistake, but easy to fix.
So [here is the link for the fix for the fix](https://github.com/RexTheCapt/EdTools/releases/tag/V0.1.2). Also please comment in here if it worked or not.

**Comment by RexTheCapt** [comment] 2022-04-05 10:11
This software has been moved to https://github.com/RexTheCapt/RatAssist so wont fix.

**Closed as completed by RexTheCapt** 2022-04-05 10:11 UTC
Labels: wontfix
